# Site settings
title: Jung Jun Hee
description: Introduction
baseurl: "/Introduction"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jung Jun Hee
user_description: <h3>안녕하세요!</h3><br>저는 동아마이스터고등학교에서 자동화·설비 분야의<br>뛰어난 엔지니어를 꿈꾸며 열심히 공부하고 있는 정준희입니다.<br>저는 전기·전자 분야와 컴퓨터 분야에 관심이 있으며<br>컴퓨터나 plc를 비롯한 장비들을 다루는 것을 좋아합니다.<hr>저에 대해 더 알고 싶으시다면 제 블로그에 방문해주시기 바랍니다.<a href="https://streetlamp0912.github.io" target="_blank">https://streetlamp0912.github.io</a>
user_title: Future engineer
email: jungjuni0912@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
